"""init tables

Revision ID: b22fbcf8d999
Revises: 1eed3e5529df
Create Date: 2023-05-26 14:43:57.496484

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b22fbcf8d999"
down_revision = "1eed3e5529df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "herbaltea",
        sa.Column("indication_ids", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("name_botanical", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_fr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("monograph_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("indication_raw", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gbif_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="api",
    )
    op.create_table(
        "indication",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("indication", schema="api")
    op.drop_table("herbaltea", schema="api")
    # ### end Alembic commands ###
